#!/bin/sh

PACKAGE_INSTALL=""
LIST_OF_APP_PATHS=""
DESTINATION_FOLDER=""

usage() {
	echo "\033[0;31mInvalid or insufficient arguments provided!\033[0;m">&2
	echo "CLI Arguments provided: $@"
	echo "\033[1;37mUSAGE:\033[0;m $0 \033[0;33m--list-of-app-paths=\033[0;m'<arguments to collector>' [\033[0;33m--package-install=\033[0;m'>arguments to apt install>']">&2
	echo "">&2
	echo "--list-of-app-paths='<arguments>'       Arguments to collector python3 script.">&2
	echo "--package-install='<package names>'  Optional: Arguments to 'apt install -y' to install packages automatically">&2
	exit 1
}

binary_is_available() {
	local t=$(which "$1")
	if [ -n "${t}" ]; then
		return 0 # true, found binary
	fi
	return 1 # false, binary was not found
}

for i in "$@"; do
	case $i in
		--package-install=*)
			PACKAGE_INSTALL="${i#*=}"
			shift
			;;
		--destination-folder=*)
			DESTINATION_FOLDER="${i#*=}"
			shift
			;;
		--list-of-app-paths=*)
			LIST_OF_APP_PATHS="${i#*=}"
			shift
			;;
		*)
			echo "\033[0;31mUnknown argument: '$i'\033[0;m">&2
			;;
	esac
done

if  [ -z "${LIST_OF_APP_PATHS}" ]; then
	usage
fi

# see https://superuser.com/a/1525721
# echo 'APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/01keep-debs
# echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' >> /etc/apt/apt.conf.d/01keep-debs
# echo 'APT::Clean-Installed "false";' > /etc/apt/apt.conf.d/01do-not-clean-installed-debs

if binary_is_available 'apk'; then
	echo "\033[0;34mInstalling collector dependencies using APK ...\033[0;m"
	apk add python3
elif binary_is_available 'apt'; then
	echo "\033[0;34mPulling info about apt sources ...\033[0;m"
	apt update -y

	echo "\033[0;34mInstalling collector dependencies using APT ...\033[0;m"
	apt install -y python3
else
	echo "\033[0;31mInstalling python3 failed.\033[0;m"
	exit 1
fi

if [ -n "${PACKAGE_INSTALL}" ]; then
	echo "\033[0;34mInstalling application and its dependencies for analysis ...\033[0;m"
	if binary_is_available "apk"; then
		apk add ${PACKAGE_INSTALL}
	elif binary_is_available "apt"; then
		# extract *.deb using ar -> https://www.cyberciti.biz/faq/how-to-extract-a-deb-file-without-opening-it-on-debian-or-ubuntu-linux/
		# apt install -y ${PACKAGE_INSTALL} --download-only
		apt install -y ${PACKAGE_INSTALL}
	fi
else
	echo "\033[0;34mNo application to collect will be installed using a package manager. You wished for this.\033[0;m"
fi

echo "\033[0;34mPreparing destination of analysis results ...\033[0;m"

if ! [ -d "${DESTINATION_FOLDER}" ]; then
	mkdir -pv "${DESTINATION_FOLDER}"
fi

for app_path in "${LIST_OF_APP_PATHS}"; do
	if [ "${app_path}" ]; then
		app_path_dir=$(dirname "${DESTINATION_FOLDER}${app_path}")
		if ! [ -d "${app_path_dir}" ]; then mkdir -p "${app_path_dir}"; fi
		echo "\033[0;34mCopying '${app_path}' ...\033[0;m"
		cp -r "$app_path" "${DESTINATION_FOLDER}${app_path}"
	fi
done

echo "\033[0;34mAnalyzing application and its dependencies ...\033[0;m"

python3 dependency-collector.py ${DESTINATION_FOLDER} ${LIST_OF_APP_PATHS}

if ! [ -d "${DESTINATION_FOLDER}/etc" ]; then
	mkdir -pv "${DESTINATION_FOLDER}/etc"
fi

echo "\033[0;34mGenerating passwd file ...\033[0;m"
echo 'root:x:0:0:root:/:/nonexistent'>${DESTINATION_FOLDER}/etc/passwd
echo 'nonroot:x:1000:1000:nonroot,,,:/nonexistent:/nonexistent'>>${DESTINATION_FOLDER}/etc/passwd

echo "\033[0;34mGenerating group file ...\033[0;m"
echo 'root:x:0:'>${DESTINATION_FOLDER}/etc/group
echo 'nonroot:x:1000:'>>${DESTINATION_FOLDER}/etc/group
